<?php

namespace Myexp\Bundle\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DownloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadRepository extends EntityRepository
{
    public function getDownloadCount($params = null) {

        $qb = $this->buildQuery($params);
        $qb->select($qb->expr()->count('a'));

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getDownloadsWithPagination($params = null, $order_by = array(), $offset = 0, $limit = 0) {
        $qb = $this->buildQuery($params);

        if ((isset($offset)) && (isset($limit))) {
            if ($limit > 0) {
                $qb->setFirstResult($offset);
                $qb->setMaxResults($limit);
            }
        }

        foreach ($order_by as $key => $value) {
            $qb->add('orderBy', $key . ' ' . $value);
        }
        $q = $qb->getQuery();
        return $q->getResult();
    }

    private function buildQuery($params) {

        $qb = $this->createQueryBuilder('a');

        if (isset($params['category'])) {
            $allChildren = $params['category']->getAllChildren();
            $qb
                    ->andWhere($qb->expr()->in('a.category', '?1'))
                    ->setParameter(1, $allChildren)
            ;
        }
        if (isset($params['isActive'])) {
            $qb
                    ->andWhere('a.isActive = ?2')
                    ->setParameter(2, $params['isActive'])
            ;
        }

        return $qb;
    }
}
