<?php

namespace Myexp\Bundle\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTranslationRepository extends EntityRepository {

    public function getCount($params = null) {

        $qb = $this->buildQuery($params);
        $qb->select($qb->expr()->count('pt'));

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getWithPagination($params = null, $order_by = array(), $offset = 0, $limit = 0) {

        $qb = $this->buildQuery($params);

        if ((isset($offset)) && (isset($limit))) {
            if ($limit > 0) {
                $qb->setFirstResult($offset);
                $qb->setMaxResults($limit);
            }
        }

        foreach ($order_by as $key => $value) {
            $qb->add('orderBy', $key . ' ' . $value);
        }

        $q = $qb->getQuery();

        return $q->getResult();
    }

    private function buildQuery($params) {

        $qb = $this->createQueryBuilder('pt');

        if (isset($params['title'])) {
            $qb
                    ->andWhere($qb->expr()->like('pt.title', '?1'))
                    ->setParameter(1, $params['title'])
            ;
        }
        
        if (isset($params['content'])) {
            $qb
                    ->orWhere($qb->expr()->like('pt.content', '?2'))
                    ->setParameter(2, $params['content'])
            ;
        }

        if (isset($params['lang'])) {
            $qb
                    ->andWhere('pt.lang = ?3')
                    ->setParameter(3, $params['lang'])
            ;
        }

        return $qb;
    }

}
