## CMS seed data
---
Website:
    - {id: 1, name: '默认站点', title: '默认网站'}

Role:
    - {id: 1, name: '管理员', role: 'ROLE_ADMIN'}
    - {id: 2, name: '普通用户', role: 'ROLE_USER'}

ContentModel:
    - {id: 1, name: 'article', title: '文章', entityName: 'MyexpCmsBundle:Article', listControllerName: 'MyexpFrontBundle:Content:list', showControllerName: 'MyexpFrontBundle:Content:show', isClassable: true}
    - {id: 2, name: 'page', title: '页面', entityName: 'MyexpCmsBundle:Page', listControllerName: 'MyexpFrontBundle:Content:list', showControllerName: 'MyexpFrontBundle:Content:show', isClassable: false}
    - {id: 3, name: 'download', title: '下载', entityName: 'MyexpCmsBundle:Download', listControllerName: 'MyexpFrontBundle:Content:list', showControllerName: 'MyexpFrontBundle:Content:show', isClassable: true}
    - {id: 4, name: 'product', title: '产品', entityName: 'MyexpCmsBundle:Product', listControllerName: 'MyexpFrontBundle:Content:list', showControllerName: 'MyexpFrontBundle:Content:show', isClassable: true}
    - {id: 5, name: 'article', title: '相册', entityName: 'MyexpCmsBundle:Album', listControllerName: 'MyexpFrontBundle:Content:list', showControllerName: 'MyexpFrontBundle:Content:show', isClassable: true}
    
ContentStatus:
    - {id: 1, name: 'approved', title: '审核通过'}

Menu:
    - {id: 1, name: 'main', title: '主菜单', website: 1, isActive: true}