imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MyexpUserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        admin_skin: skin-blue-light
    form_themes:
        # other form themes
        - 'VichUploaderBundle:Form:fields.html.twig'
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Configuration
# # http://symfony.com/doc/current/cookbook/assetic/asset_management.html
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        uglifyjs2:
            # the path to the uglifyjs executable
            bin: %kernel.root_dir%/Resources/node_modules/.bin/uglifyjs
        uglifycss:
            # the path to the uglifycss executable
            bin: %kernel.root_dir%/Resources/node_modules/.bin/uglifycss

# FOSUserBunlde configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Myexp\Bundle\UserBundle\Entity\User
    group:
        group_class: Myexp\Bundle\UserBundle\Entity\Group
    resetting:
        form:
            type: Myexp\Bundle\UserBundle\Form\ResettingFormType
    profile:
        form:
            type: Myexp\Bundle\UserBundle\Form\UserType

# Doctrine Migration Bundle configurations
# http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# LiipImagineBundle image filters
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        profile_picture:
            quality: 90
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

# KNP Menu configuration
# http://symfony.com/doc/master/bundles/KnpMenuBundle/index.html
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

# File Uploader Bundle configuration
#https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/installation.md
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        profile_image:
            uri_prefix:         /images/profile
            upload_destination: '%kernel.root_dir%/../web/images/profile'
            namer: vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

#https://github.com/whiteoctober/BreadcrumbsBundle
white_october_breadcrumbs:
    separator: ''

avanzu_admin_theme:
    #bower_bin: C:\Users\{username}\AppData\Roaming\npm\bower.cmd # that's the default value
    bower_bin: /usr/local/bin/bower #for linux system
    
ivory_ck_editor:
    default_config: default
    configs:
        default:
            uiColor: "#FFFFFF"
            filebrowserBrowseRoute: "finder_ckeditor"
