# this imports the routes used to display the web debug toolbar at the bottom of each page
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

# this imports the routes needed to display the Symfony Profiler information
_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

# this loads the main routing file, which usually defines the routes available
# in any environment (production, development, etc.)
_main:
    resource: routing.yml
