services:
    
    myexp_user_bundle.user_profile_listener:
        class: Myexp\Bundle\UserBundle\EventListener\UserProfileListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }
            - { name: kernel.event_listener, event: theme.sidebar_user, method: onShowUser }
            
    myexp_user.resetting.form.type:
        class: Myexp\Bundle\UserBundle\Form\ResettingFormType
        tags:
            - { name: form.type, alias: myexp_user_resetting }

    myexp_user.profile.form.type:
        class: Myexp\Bundle\UserBundle\Form\UserType
        tags:
            - { name: form.type, alias: myexp_user_profile }