default:
    resource: "@CmsBundle/Controller/DefaultController.php"
    type: annotation

user_check:
    path: /user/check
    
user_logout:
    path: /user/logout
    
user:
    resource: "@CmsBundle/Controller/UserController.php"
    type: annotation
    
#category:
#    resource: "@CmsBundle/Controller/CategoryController.php"
#    type: annotation
    
#page:
#    resource: "@CmsBundle/Controller/PageController.php"
#    type: annotation
    
#album:
#    resource: "@CmsBundle/Controller/AlbumController.php"
#    type: annotation
     
#link:
#    resource: "@CmsBundle/Controller/LinkController.php"
#    type: annotation
    
#menu:
#    resource: "@CmsBundle/Controller/MenuController.php"
#    type: annotation
    
#photo:
#    resource: "@CmsBundle/Controller/PhotoController.php"
#    type: annotation

#search:
#    resource: "@CmsBundle/Controller/SearchController.php"
#    type: annotation
    
#download:
#    resource: "@CmsBundle/Controller/DownloadController.php"
#    type: annotation
    
#slider:
#    resource: "@CmsBundle/Controller/SliderController.php"
#    type: annotation

#product:
#    resource: "@CmsBundle/Controller/ProductController.php"
#    type: annotation

admin_default:
    resource: "@CmsBundle/Controller/Admin/DefaultController.php"
    type: annotation

admin_article:
    resource: "@CmsBundle/Controller/Admin/ArticleController.php"
    type: annotation
    
admin_page:
    resource: "@CmsBundle/Controller/Admin/PageController.php"
    type: annotation

admin_product:
    resource: "@CmsBundle/Controller/Admin/ProductController.php"
    type: annotation

admin_album:
    resource: "@CmsBundle/Controller/Admin/AlbumController.php"
    type: annotation

admin_user:
    resource: "@CmsBundle/Controller/Admin/UserController.php"
    type: annotation