myexp_rewrite:
    resource: .
    type: rewrite

default:
    resource: "@MyexpCmsBundle/Controller/DefaultController.php"
    type: annotation

user_check:
    path: /user/check
    
user_logout:
    path: /user/logout
    
user:
    resource: "@MyexpCmsBundle/Controller/UserController.php"
    type: annotation
    

    
#page:
#    resource: "@MyexpCmsBundle/Controller/PageController.php"
#    type: annotation
    
#album:
#    resource: "@MyexpCmsBundle/Controller/AlbumController.php"
#    type: annotation
     

    
#menu:
#    resource: "@MyexpCmsBundle/Controller/MenuController.php"
#    type: annotation
    
#photo:
#    resource: "@MyexpCmsBundle/Controller/PhotoController.php"
#    type: annotation

#search:
#    resource: "@MyexpCmsBundle/Controller/SearchController.php"
#    type: annotation
   
    


#product:
#    resource: "@MyexpCmsBundle/Controller/ProductController.php"
#    type: annotation

admin_default:
    resource: "@MyexpCmsBundle/Controller/Admin/DefaultController.php"
    type: annotation

admin_article:
    resource: "@MyexpCmsBundle/Controller/Admin/ArticleController.php"
    type: annotation
    
admin_page:
    resource: "@MyexpCmsBundle/Controller/Admin/PageController.php"
    type: annotation

admin_download:
    resource: "@MyexpCmsBundle/Controller/Admin/DownloadController.php"
    type: annotation

admin_product:
    resource: "@MyexpCmsBundle/Controller/Admin/ProductController.php"
    type: annotation

admin_album:
    resource: "@MyexpCmsBundle/Controller/Admin/AlbumController.php"
    type: annotation

admin_user:
    resource: "@MyexpCmsBundle/Controller/Admin/UserController.php"
    type: annotation

admin_link:
    resource: "@MyexpCmsBundle/Controller/Admin/LinkController.php"
    type: annotation

admin_website:
    resource: "@MyexpCmsBundle/Controller/Admin/WebsiteController.php"
    type: annotation
    
admin_category:
    resource: "@MyexpCmsBundle/Controller/Admin/CategoryController.php"
    type: annotation
    
admin_slider:
    resource: "@MyexpCmsBundle/Controller/Admin/SliderController.php"
    type: annotation