services:
    # 登录监听器，记录用户最后一次登录时间
    # 以及登录次数
    myexp_cms.listener.login_listener:
        class: 'Myexp\Bundle\CmsBundle\EventListener\LoginListener'
        arguments: ['@doctrine']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
    
    # 本地化监听器，用于设置全局locale
    myexp_cms.listener.locale_listener:
        class: 'Myexp\Bundle\CmsBundle\EventListener\LocaleListener'
        arguments: [%myexp_cms.enabled_locales%, %locale%]
        tags:
            - { name: kernel.event_subscriber}
            
    # 视图监听器，用于设置全局变量
    myexp_cms.listener.view_listener:
        class: 'Myexp\Bundle\CmsBundle\EventListener\ViewListener'
        arguments: ['@doctrine', %myexp_cms.url_rewrite%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
            
    # 注册实体ID转换表单类型
    myexp_cms.form.entity_id_type:
        class: 'Myexp\Bundle\CmsBundle\Form\Type\EntityIdType'
        arguments: ['@doctrine']
        tags:
            - { name: form.type, alias: entity_id }
    
    # 自定义路由加载器，加载内容类型默认路由以及URL别名
    myexp_cms.routing_loader:
        class: 'Myexp\Bundle\CmsBundle\Routing\RewriteLoader'
        arguments: ['@doctrine', %myexp_cms.url_rewrite%]
        tags:
            - { name: routing.loader }
            
    # 分类选择器
    myexp_cms.form.category_type:
        class: Myexp\Bundle\CmsBundle\Form\Type\CategoryType
        arguments: ['@doctrine']
        tags:
            - { name: form.type, alias: category}
            
    # 日期时间选择器
    myexp_cms.form.datetime_type:
        class: Myexp\Bundle\CmsBundle\Form\Type\DateTimeType
        arguments: [%locale%]
        tags:
            - { name: form.type, alias: datetime}