services:
    
    slugger:
        class: Myexp\Bundle\CmsBundle\Utils\Slugger

    markdown:
        class: Myexp\Bundle\CmsBundle\Utils\Markdown
        
    cms.twig.app_extension:
        public:    false
        class:     Myexp\Bundle\CmsBundle\Twig\AppExtension
        arguments: ['@markdown', %app_locales%]
        tags:
            - { name: twig.extension }
        
    cms.twig.extension:
        class: Myexp\Bundle\CmsBundle\Twig\CmsExtension
        tags:
            - { name: twig.extension }
            
    cms.listener.login_listener:
        class: 'Myexp\Bundle\CmsBundle\EventListener\LoginListener'
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            
    cms.listener.locale_listener:
        class: 'Myexp\Bundle\CmsBundle\EventListener\LocaleListener'
        arguments: ['@router', %myexp_cms.locales%, %locale%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            
    cms.form.entity_id_type:
        class: 'Myexp\Bundle\CmsBundle\Form\Type\EntityIdType'
        arguments: ['@doctrine']
        tags:
            - { name: form.type, alias: entity_id }
            
