<?php

namespace Myexp\Bundle\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function findAllOrderByName() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT u FROM MyexpUserBundle:User u ORDER BY u.first_name ASC'
                        )
                        ->getResult();
    }

}
