<?php

namespace Myexp\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository {

    /**
     * 构造查询
     * 
     * @param type $params
     * @return type
     */
    protected function buildContentQuery(\Doctrine\ORM\QueryBuilder $qb, $params) {

        $qb->join('q.content', 'c');

        if (!isset($params['content'])) {
            return $qb;
        }

        //标题
        if (isset($params['content']['title'])) {
            $qb
                    ->andWhere($qb->expr()->like('c.title', ':title'))
                    ->setParameter('title', '%' . $params['content']['title'] . '%')
            ;
        }

        //状态
        if (isset($params['content']['status'])) {
            $qb
                    ->andWhere('c.contentStatus = :status')
                    ->setParameter('status', $params['content']['status'])
            ;
        }

        return $qb;
    }

}
