<?php

namespace Myexp\Bundle\AdminBundle\Repository;

/**
 * QueryUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlAliasRepository extends \Doctrine\ORM\EntityRepository {
    
}
