<?php

namespace Myexp\Bundle\CmsBundle\Repository;

use Myexp\Bundle\AdminBundle\Repository\ContentRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends ContentRepository {

    /**
     * 获得分页查询
     * 
     * @param type $params
     * @return type
     */
    public function getPaginationQuery($params = null) {
        $qb = $this->buildQuery($params);
        $qb->addOrderBy('q.publishTime', 'DESC');

        return $qb->getQuery();
    }

    /**
     * 构造查询
     * 
     * @param type $params
     * @return type
     */
    public function buildQuery($params) {

        $qb = $this->createQueryBuilder('q');

        //添加内容过滤
        $this->buildContentQuery($qb, $params);
        
        //分类
        if (isset($params['category'])) {
            $allChildren = $params['category']->getAllChildren();
            $qb
                    ->andWhere($qb->expr()->in('q.category', ':category'))
                    ->setParameter('category', $allChildren)
            ;
        }

        //作者
        if (isset($params['author'])) {
            $qb
                    ->andWhere('author =  :author')
                    ->setParameter('author', $params['author'])
            ;
        }

        return $qb;
    }

}
