<?php

namespace Myexp\Bundle\CmsBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ContentModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentModelRepository extends EntityRepository {

    /**
     * 
     * 获得可分类的数据模型
     * 
     * @return type
     */
    public function getClassableModels() {

        $query = $this
                ->createQueryBuilder('cm')
                ->where('cm.isClassable = true')
                ->getQuery()
        ;

        return $query->execute();
    }

}
