<?php

namespace Myexp\Bundle\CmsBundle\Repository;

/**
 * ContentStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
