<?php

namespace Myexp\Bundle\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Routing\Route;
use Symfony\Component\Routing\RouteCollection;

/**
 * DownloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadRepository extends EntityRepository  implements ContentModel{

    /**
     * 获得默认路由
     * 
     * @return RouteCollection
     */
    public function getDefaultRoute($urlSurffix) {

        $routes = new RouteCollection();

        $path = '/download/{id}' . $urlSurffix;
        $defaults = array(
            '_controller' => 'MyexpCmsBundle:Download:show'
        );
        $requirements = array(
            'id' => '\d+'
        );
        $route = new Route($path, $defaults, $requirements);

        $routeName = 'download_show';
        $routes->add($routeName, $route);

        return $routes;
    }
    
    /**
     * 获得分页查询
     * 
     * @param type $params
     * @return type
     */
    public function getPaginationQuery($params = null) {
        $qb = $this->buildQuery($params);

        return $qb->getQuery();
    }

    /**
     * 构造查询
     * 
     * @param type $params
     * @return type
     */
    public function buildQuery($params) {

        $qb = $this->createQueryBuilder('d');

        return $qb;
    }

}
