<?php

namespace Myexp\Bundle\CmsBundle\Repository;

/**
 * DownloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadRepository extends \Doctrine\ORM\EntityRepository {
    
}
