<?php

namespace Myexp\Bundle\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository {

    public function getLinks($limit) {

        $qb = $this
                ->createQueryBuilder('l')
                ->add('orderBy', 'l.sortOrder ASC')
                ->setMaxResults($limit)
        ;

        $q = $qb->getQuery();

        return $q->getResult();
    }
    
    public function getAlllinks() {
        $qb = $this
                ->createQueryBuilder('s')
                ->where('s.isActive = :isActive')
                ->setParameter('isActive', true)
                ->orderBy('s.sortOrder','ASC')
                ->getQuery()
        ;
        return $qb->getResult();
    }

}
