<?php

namespace Myexp\Bundle\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Routing\Route;
use Symfony\Component\Routing\RouteCollection;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository implements ContentModel {

    /**
     * 获得默认路由
     * 
     * @return RouteCollection
     */
    public function getDefaultRoute($urlSurffix) {

        $routes = new RouteCollection();

        $path = '/page/{id}' . $urlSurffix;
        $defaults = array(
            '_controller' => 'MyexpCmsBundle:Page:show'
        );
        $requirements = array(
            'id' => '\d+'
        );
        $route = new Route($path, $defaults, $requirements);

        $routeName = 'page_show';
        $routes->add($routeName, $route);

        return $routes;
    }
    
    /**
     * 获得分页查询
     * 
     * @param type $params
     * @return type
     */
    public function getPaginationQuery($params = null) {
        $qb = $this->buildQuery($params);

        return $qb->getQuery();
    }

    public function getPageCount($params = null) {

        $qb = $this->buildQuery($params);
        $qb->select($qb->expr()->count('a'));

        return $qb->getQuery()->getSingleScalarResult();
    }

    private function buildQuery($params) {

        $qb = $this->createQueryBuilder('a');

        if (isset($params['page'])) {
            $qb
                    ->andWhere('a.page = ?1')
                    ->setParameter(1, $params['page'])
            ;
        }
        if (isset($params['isActive'])) {
            $qb
                    ->andWhere('a.isActive = ?2')
                    ->setParameter(2, $params['isActive'])
            ;
        }

        return $qb;
    }

}
