<?php

namespace Myexp\Bundle\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository {
    
    
    public function getPageCount($params = null) {

        $qb = $this->buildQuery($params);
        $qb->select($qb->expr()->count('a'));

        return $qb->getQuery()->getSingleScalarResult();
    }
    
        public function getPagesWithPagination($params = null, $order_by = array(), $offset = 0, $limit = 0) {

        $qb = $this->buildQuery($params);

        if ((isset($offset)) && (isset($limit))) {
            if ($limit > 0) {
                $qb->setFirstResult($offset);
                $qb->setMaxResults($limit);
            }
        }

        foreach ($order_by as $key => $value) {
            $qb->add('orderBy', $key . ' ' . $value);
        }

        $q = $qb->getQuery();

        return $q->getResult();
    }
    
    private function buildQuery($params) {

        $qb = $this->createQueryBuilder('a');

        if (isset($params['page'])) {
            $qb
                    ->andWhere('a.page = ?1')
                    ->setParameter(1, $params['page'])
            ;
        }
        if (isset($params['isActive'])) {
            $qb
                    ->andWhere('a.isActive = ?2')
                    ->setParameter(2, $params['isActive'])
            ;
        }

        return $qb;
    }
}
