<?php

namespace Myexp\Bundle\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository {

    public function getPhotoCount($params = null) {

        $qb = $this->buildQuery($params);
        $qb->select($qb->expr()->count('p'));

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getPhotosWithPagination($params = null, $order_by = array(), $offset = 0, $limit = 0) {

        $qb = $this->buildQuery($params);

        if ((isset($offset)) && (isset($limit))) {
            if ($limit > 0) {
                $qb->setFirstResult($offset);
                $qb->setMaxResults($limit);
            }
        }

        foreach ($order_by as $key => $value) {
            $qb->add('orderBy', $key . ' ' . $value);
        }

        $q = $qb->getQuery();

        return $q->getResult();
    }

    private function buildQuery($params) {

        $qb = $this->createQueryBuilder('p');

        if (isset($params['album'])) {
            $qb
                    ->andWhere('p.album = ?1')
                    ->setParameter(1, $params['album'])
            ;
        }
        if (isset($params['isActive'])) {
            $qb
                    ->andWhere('p.isActive = ?2')
                    ->setParameter(2, $params['isActive'])
            ;
        }

        return $qb;
    }
    
    //幻灯$id为相册id
    public function getSlider($id){
        $qb=  $this->createQueryBuilder('s')
                ->where('s.album = :album','s.isActive = :isActive')
                ->setParameters(array('album'=>$id,'isActive'=>TRUE))
                ->orderBy('s.id')
                ->getQuery()
                ;
                return $qb->getResult();
              
    }

}
