<?php

namespace Myexp\Bundle\CmsBundle\Repository;

use Myexp\Bundle\AdminBundle\Repository\ContentRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends ContentRepository {

    /**
     * 获得分页查询
     * 
     * @param type $params
     * @return type
     */
    public function getPaginationQuery($params = null) {
        $qb = $this->buildQuery($params);
        $qb->addOrderBy('c.createTime', 'DESC');

        return $qb->getQuery();
    }

    /**
     * 构造查询
     * 
     * @param type $params
     * @return type
     */
    private function buildQuery($params) {

        $qb = $this->createQueryBuilder('q');

        //添加内容过滤
        $this->buildContentQuery($qb, $params);

        if (isset($params['category'])) {
            $allChildren = $params['category']->getAllChildren();
            $qb
                    ->andWhere($qb->expr()->in('q.category', ':category'))
                    ->setParameter('category', $allChildren)
            ;
        }
        
        if (isset($params['isActive'])) {
            $qb
                    ->andWhere('p.isActive = ?2')
                    ->setParameter(2, $params['isActive'])
            ;
        }

        return $qb;
    }

}
